name: clean

on:
  pull_request:
    types: [closed]

# Ensures PR cleanup workflow has minimal permissions for security
permissions:
  contents: read        # Read-only access to repo contents for safer workflows
  pull-requests: write  # Allow workflow to comment on, label, and update pull request as part of automation
  id-token: write       # Allow OIDC tokens for secure cloud authentication

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@9ebb0c8894f693c412243968f73cb1ae3910cecf
    concurrency:
      group: ci-preview-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    with:
      hosting_provider: ${{ vars.HOSTING_PROVIDER }}
      app_name: flask-react-app
      app_env: preview
      branch: pr-${{ github.event.pull_request.number }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      aws_cluster_name: ${{ vars.AWS_CLUSTER_NAME }}
      aws_region: ${{ vars.AWS_REGION }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
